version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
#    depends_on:
#      - db
#  db:
#    image: sqlite:3
#    volumes:
#      - ./my_database.db:/data/my_database.db